// FORM MANAGEMENT //
export const HANDLE_FAILED_FORM_SUBMIT = "HANDLE_FAILED_FORM_SUBMIT";
export const HANDLE_FORM_SUBMIT = "HANDLE_FORM_SUBMIT";
export const INITIATE_FORM_SUBMIT = "INITIATE_FORM_SUBMIT";
export const COMPLETE_FORM_SUBMIT = "COMPLETE_FORM_SUBMIT";

// BUTTON MANAGEMENT //
export const INITIATE_BUTTON_CLICK = "INITIATE_BUTTON_CLICK";
export const COMPLETE_BUTTON_CLICK = "COMPLETE_BUTTON_CLICK";

// SERVER MANAGEMENT //
export const TOGGLE_SERVER = "TOGGLE_SERVER";
export const GET_SERVER_STATUS = "GET_SERVER_STATUS";
export const GET_BUTTON_MESSAGE = "GET_BUTTON_MESSAGE";
export const GET_USER_SESSION = "GET_USER_SESSION";

// AUTHORIZATION //

// API
export const GET_API_KEY = "GET_API_KEY";

// GENERAL LOGIN
export const INITIAL_USER_SESSION = "INITIAL_USER_SESSION";
export const INITIATE_NEW_PASSWORD_CHALLENGE =
  "INITIATE_NEW_PASSWORD_CHALLENGE";
export const HANDLE_FAILED_LOGIN = "HANDLE_FAILED_LOGIN";
export const HANDLE_SUCCESSFUL_LOGIN = "HANDLE_SUCCESSFUL_LOGIN";
export const SIGN_OUT_USER = "SIGN_OUT_USER";

// CHANGE PASSWORD
export const REDIRECT_TO_CHANGE_PASSWORD = "REDIRECT_TO_CHANGE_PASSWORD";
export const COMPLETE_REDIRECT_TO_CHANGE_PASSWORD =
  "COMPLETE_REDIRECT_TO_CHANGE_PASSWORD";
export const MARK_PASSWORD_CHANGED = "MARK_PASSWORD_CHANGED";
export const UNMARK_PASSWORD_CHANGED = "UNMARK_PASSWORD_CHANGED";
export const MARK_PASSWORDS_DO_NOT_MATCH = "MARK_PASSWORDS_DO_NOT_MATCH";
export const UNMARK_PASSWORDS_DO_NOT_MATCH = "UNMARK_PASSWORDS_DO_NOT_MATCH";
export const CLEAR_LOGIN_ERROR_MESSAGE = "CLEAR_LOGIN_ERROR_MESSAGE";

// WIDGETS //

// TIMER
export const GET_STOP_TIME = "GET_STOP_TIME";
export const DECREASE_TIMER = "DECREASE_TIMER";
export const INCREASE_TIMER = "INCREASE_TIMER";

// PLAYERS
export const GET_PLAYERS = "GET_PLAYERS";

// MAP //
export const GET_WINDOW_HEIGHT = "GET_WINDOW_HEIGHT";
